name: Check pull request

on:
    pull_request:
        types:
            - opened
            - synchronize
        branches:
            - develop

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version-file: go.mod

            - name: Run tests
              run: go test ./... -v -race

    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version-file: go.mod

            - name: Run golangci-lint
              uses: golangci/golangci-lint-action@v6
              with:
                  version: latest
